### ISSUE TITLE
FileNotFoundException on Linux

### ISSUE THREAD

**Issue by achtzwan** [Ultz/Silk.NET#155]
# Summary
Examples which needs .frag and .vert files won't start due to a "FileNotFoundException".

.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

# Exception
dotnet run
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/manuel/Downloads/Silk.NET/examples/CSharp/tutorial1.3/shader.vert'.
File name: '/home/manuel/Downloads/Silk.NET/examples/CSharp/tutorial1.3/shader.vert'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Tutorial.Shader.LoadShader(ShaderType type, String path) in /home/manuel/Downloads/Silk.NET/examples/CSharp/Tutorial 1.3 - Abstractions/Shader.cs:line 86
   at Tutorial.Shader..ctor(GL gl, String vertexPath, String fragmentPath) in /home/manuel/Downloads/Silk.NET/examples/CSharp/Tutorial 1.3 - Abstractions/Shader.cs:line 21
   at Tutorial.Program.OnLoad() in /home/manuel/Downloads/Silk.NET/examples/CSharp/Tutorial 1.3 - Abstractions/Program.cs:line 72
   at Silk.NET.Windowing.Desktop.GlfwWindow.Initialize()
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Tutorial.Program.Main(String[] args) in /home/manuel/Downloads/Silk.NET/examples/CSharp/Tutorial 1.3 - Abstractions/Program.cs:line 49

- As an attachment:
Please stop using whitespaces in directory/file names, it's annoying and painful on Linux.

**Comment by devvoid** [comment]
Looks like the shaders had their names changed (`shader.vert` -> `Shader.vert`) without updating the paths in the code itself. Will PR this immediately.

As for whitespace in the directory names, please open another issue for discussion on this.

Thank you for the report!
