### ISSUE TITLE
Vulkan Example Project Messenger EntryPointNotFoundException

### ISSUE THREAD

**Issue by dlzawap** [Ultz/Silk.NET#158]
# Summary
Creating DebugUtilsMessenger in "src/Labs/VulkanTriangle" Project will throw EntryPointNotFoundException.

# Steps to reproduce
1. Activate ValidationLayers
2. Build & Run
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

src/Lab/VulkanTriangle/HelloTriangleApplication.cs
Line 290 will throw an EntryPointNotFoundException
 ```csharp
fixed (DebugUtilsMessengerEXT* debugMessenger = &_debugMessenger)
            {
                if (_debugUtils.CreateDebugUtilsMessenger
                        (_instance, &createInfo, null, debugMessenger) != Result.Success)
                {
                    throw new Exception("Failed to create debug messenger.");
                }
            }
```

```/usr/share/dotnet/dotnet /home/manuel/Downloads/Silk.NET/src/Lab/VulkanTriangle/bin/Debug/netcoreapp3.0/VulkanTriangle.dll
Unhandled exception. System.EntryPointNotFoundException: Entry point was not found.
   at Silk.NET.Vulkan.VkLoader.CoreLoadFunctionPointer(IntPtr library, String symbolName) in /home/manuel/Downloads/Silk.NET/src/Vulkan/Silk.NET.Vulkan/VkLoader.cs:line 64
   at Ultz.SuperInvoke.Loader.LibraryLoader.LoadFunctionPointer(IntPtr handle, String functionName)
   at Ultz.SuperInvoke.Loader.UnmanagedLibrary.LoadFunction(String name)
   at Ultz.SuperInvoke.NativeApiContainer.Load(Int32 slot, String entryPoint)
   at Silk.NET.Vulkan.Extensions.EXT.XB5930714.ExtDebugUtils.CreateDebugUtilsMessenger(Instance , DebugUtilsMessengerCreateInfoEXT* , AllocationCallbacks* , DebugUtilsMessengerEXT* )
   at VulkanTriangle.HelloTriangleApplication.SetupDebugMessenger() in /home/manuel/Downloads/Silk.NET/src/Lab/VulkanTriangle/HelloTriangleApplication.cs:line 290
   at VulkanTriangle.HelloTriangleApplication.InitVulkan() in /home/manuel/Downloads/Silk.NET/src/Lab/VulkanTriangle/HelloTriangleApplication.cs:line 89
   at VulkanTriangle.HelloTriangleApplication.Run() in /home/manuel/Downloads/Silk.NET/src/Lab/VulkanTriangle/HelloTriangleApplication.cs:line 30
   at VulkanTriangle.Program.Main(String[] args) in /home/manuel/Downloads/Silk.NET/src/Lab/VulkanTriangle/Program.cs:line 11

Process finished with exit code 134.
```

**Comment by Perksey** [comment]
The validation layers were disabled because I had no idea how to fix this issue 😂 the aim of the program was just to prove the bindings worked anyway, but I do need to give this a look at some point

**Comment by Perksey** [comment]
Turns out we weren't enabling the extension when creating the instance. I've updated the VulkanTriangle application, as well as the exception message so that it hints towards you not enabling the extension properly.
