### ISSUE TITLE
Examples crash on MacOS

### ISSUE THREAD

**Issue by Rjvs** [Ultz/Silk.NET#270]
# Summary
Examples 3.2 & up all crash on MacOS 10.15.6.

# Steps to reproduce
- Platform: MacOS 10.15.6
- Framework Version: .NET Core 3.0
1. `./generator.sh`
2. `dotnet build`
3. `cd examples/CSharp/Tutorial 3.2 - Diffuse Lighting/bin/Debug/netcoreapp3.0/`
4. `dotnet Tutorial.dll`
```Unhandled exception. System.Exception: Program failed to link with error: WARNING: Output of vertex shader 'fPos' not read by fragment shader
WARNING: Output of vertex shader 'fNormal' not read by fragment shader

   at Tutorial.Shader..ctor(GL gl, String vertexPath, String fragmentPath) in /Users/rj/Code/Silk.NET/examples/CSharp/Tutorial 3.2 - Diffuse Lighting/Shader.cs:line 28
   at Tutorial.Program.OnLoad() in /Users/rj/Code/Silk.NET/examples/CSharp/Tutorial 3.2 - Diffuse Lighting/Program.cs:line 127
   at Silk.NET.Windowing.Desktop.GlfwWindow.Initialize() in /Users/rj/Code/Silk.NET/src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs:line 607
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view) in /Users/rj/Code/Silk.NET/src/Windowing/Silk.NET.Windowing.Common/WindowExtensions.cs:line 46
   at Tutorial.Program.Main(String[] args) in /Users/rj/Code/Silk.NET/examples/CSharp/Tutorial 3.2 - Diffuse Lighting/Program.cs:line 97
[1]    29891 abort      dotnet Tutorial.dll
```

# Comments
I'm testing this because we are encountering a problem with a project that uses Silk.Net https://github.com/ImpromptuNinjas/UltralightSharp

**Comment by Tyler-IN** [comment]
GLFW.CreateWindow returns a null pointer indicating failure, goes unchecked.

**Comment by Perksey** [comment]
I shall investigate this later today.

**Comment by Perksey** [comment]
Also what @Tyler-IN suggested should be unnecessary if it’s a graphics API issue - 99% of the time you don’t need to touch GLFW manually, our windowing system handles most needs.

You can change the the graphics API using the `API` property in the window options.

Though, I’m not sure if this is the actual cause and I’ll try and see if I can reproduce it on my iMac.

**Comment by Perksey** [comment]
Can reproduce, relatively easy fix. There is no issue here, it's just we were throwing on receipt of any program logs even if link status was successful

**Comment by Rjvs** [comment]
Thanks @Perksey confirm that applying that fix WFM.

**Comment by Perksey** [comment]
Awesome, never realised how sharp our examples look on Retina displays (then again, the monitors I have for my PC are awful)
